[development]
address = "0.0.0.0"
port = 80
workers = 4
log = "normal"

[staging]
address = "0.0.0.0"
port = 80
workers = 4
log = "normal"

[production]
address = "0.0.0.0"
port = 3000
workers = 4
log = "critical"
